### ISSUE TITLE
Экран "профиль"

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#12]
В профиль нужно добавить функции: 

1) Выбор диеты по соотношению бжу или же установить кастомные значения

2) Установка собственной нормы по потреблению грамм БЖУ и калорий.

3) Выход из аккаунта

**Comment by MAXBAF1** [comment]
Все функции работают

![Image](https://user-images.githubusercontent.com/63009846/236439436-9e093873-4467-4387-8a4d-10c55a5bdc7d.png)
