### ISSUE TITLE
Главный экран, правки

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#15]
1) Поменять местами кнопки поиск и статистика
2) Убрать фото и имя пользователя с главного экрана
3) Заменить надпись search сверху на SpoonVoice

**Comment by MAXBAF1** [comment]
- Сделано


![Image](https://user-images.githubusercontent.com/63009846/236438584-f193adb8-406a-4e27-8894-86ce2c8ff505.png)
