### ISSUE TITLE
Черновой дизайн

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#22]
Экраны: главный, поиск, статистика, профиль

1) Продумать что должен содержать каждый экран
2) В соответствии с пунктом 1 создать черновой дизайн + кликабельную версию

**Comment by WilgardWolf** [comment]
Черновики https://www.figma.com/file/wdKYTzqumvwSmEUkeYJHhp/Черновики?node-id=0-1&t=7u9ifcn3FMaTLtHS-0
Прототип (черновик) https://www.figma.com/file/WMm2NbnbCsNYfgcuNm3buW/Прототип(черновик)?t=7u9ifcn3FMaTLtHS-0
