### ISSUE TITLE
Дизайн, правки №1

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#23]
1) Оставляем 1 и 2 вариант диаграммы 
2) Оставляем 3 вариант рациона, переименовать его в "Недавние"
3) Вернуть значок лупа на кнопку экрана поиска, вернуть значок микрофона на кнопку голосового помощника
4) Раздвинуть картинку в информации о блюде и оформить БЖУ
5) Пометить диеты цветами БЖУ из диаграммы, убрать плашку кастомизации диеты в "моя диета" 
6) Поместить даты под график статистики, сделать подписи, чтобы было понятно что это за цифры (% и даты)
7) В статистике убрать день, сделать выпадающий список
8) Добавить кнопку удаления блюда
9) Сделать одинаковые шрифты, оставить несколько размеров
10) Поработать с цветовой гаммой, сделать поменьше различных цветов 
11) Убрать синий прямоугольник сверху, поднять элементы экрана там, где нужно.

**Comment by MAXBAF1** [comment]
![Image](https://github.com/MAXBAF1/AllFoodRetrofit/assets/63009846/f33e3c41-b82c-42cc-8362-02c9f00d3544)

**Comment by WilgardWolf** [comment]
https://www.figma.com/file/ECFV7WPXQSdyYMIHVRe2bW/Прототип(правки)?type=design&node-id=0-1&t=t65t6c0Cqbt2ozaG-0
