### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#4]
Создать векторный логотип для приложения.

Логотип должен быть простым, ярким, а также должен ассоциироваться с голосовым помощником и едой.

Дедлайн 09.04

**Comment by WilgardWolf** [comment]
https://www.figma.com/file/tIIHQkdhIzkyZgsOW4VIdT/Лого?node-id=0-1&t=NJvVMuIxQngGiDC4-0
