### ISSUE TITLE
Добавление приёма пищи

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#7]
Сделать возможность добавления съеденного продукта и подсчёта кбжу

Схема реализации есть на миро "Учесть кбжу продукта"

Не забывайте о том, что перед добавлением пользователь должен указать кол-во грамм

Ссылка на миро: https://miro.com/app/board/uXjVMb11kuE=/

**Comment by MAXBAF1** [comment]
Добавление съеденного продукта реализовано с возможностью указать количество грамм, подсчёт кбжу реализован

![Image](https://user-images.githubusercontent.com/63009846/232319766-6de2bb07-1449-49b8-ba40-1b6998c49be5.png)


![Image](https://user-images.githubusercontent.com/63009846/232319995-1af0769d-91f7-4d96-a23e-3dd1911af32e.png)



Текущая ветка: https://github.com/MAXBAF1/AllFoodRetrofit/tree/Refactor_FireBase_class
