### ISSUE TITLE
Навигация

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#8]
Реализовать переключение между экранами с помощью BottomNavigation.

**Comment by MAXBAF1** [comment]
https://github.com/MAXBAF1/AllFoodRetrofit/tree/Firebase_and_homeFragment_changing


**1 версия**
![Image](https://user-images.githubusercontent.com/63009846/231518600-7cfd73aa-5b22-4800-95f8-df9a66a0c367.png)
