### ISSUE TITLE
Визуализация БЖУ (диаграмма)

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/AllFoodRetrofit#9]
Добавить горизонтальную столбчатую диаграмму БЖУ с подписями (белки/жиры/углеводы + потребленное количество + суточная норма)

**Comment by MAXBAF1** [comment]
Сделано таким образом

![Image](https://user-images.githubusercontent.com/63009846/236439116-8a0dc27f-d428-4d3a-88c1-0c32ac352602.png)
